name: icomoon_download
description: >-
  A tool to download icomoon icons from icomoon.io and generate a dart file to use in Flutter (using icomoon_generator package)
  Provides an API and a CLI tool.
version: 1.0.0
homepage: https://github.com/thanhhaidev/icomoon_download

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.6.0
  dart_style: ^3.0.1
  dio: ^5.8.0+1
  icomoon_generator: ^1.0.3
  logger: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^5.0.0

executables:
  generator: generator